CREATE TABLE `comics` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `slug` varchar(100) DEFAULT NULL,
  `title` varchar(100) DEFAULT NULL,
  `sublog` mediumtext,
  `tooltip` varchar(255) DEFAULT NULL,
  `image` varchar(200) DEFAULT NULL,
  `thumbnail` varchar(50) DEFAULT NULL,
  `comic_width` int(5) DEFAULT '625',
  `comic_height` int(5) DEFAULT NULL,
  `post_on` datetime DEFAULT NULL,
  `posted_on` datetime DEFAULT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT '0',
  `ga_sessions` int(11) DEFAULT '0',
  `ga_pageviews` int(11) DEFAULT '0',
  `ga_metrics_updated_on` datetime DEFAULT NULL,
  `reddit_upvotes` int(11) NOT NULL DEFAULT '0',
  `reddit_published_on_http` tinyint(1) DEFAULT '0',
  `reddit_metrics_updated_on` datetime DEFAULT NULL,
  `reddit_url` varchar(255) DEFAULT NULL,
  `cheez_asset_id` varchar(50) DEFAULT NULL,
  `cheez_upvotes` int(11) NOT NULL DEFAULT '0',
  `cheez_url` varchar(255) DEFAULT NULL,
  `cheez_metrics_updated_on` datetime DEFAULT NULL,
  `9gag_upvotes` int(11) NOT NULL DEFAULT '0',
  `9gag_title` varchar(100) DEFAULT NULL,
  `9gag_url` varchar(255) DEFAULT NULL,
  `9gag_metrics_updated_on` datetime DEFAULT NULL,
  `facebook_likes` int(11) NOT NULL DEFAULT '0',
  `facebook_metrics_updated_on` datetime DEFAULT NULL,
  `tumblr_notes` int(11) NOT NULL DEFAULT '0',
  `tumblr_title` text,
  `tumblr_url` varchar(255) DEFAULT NULL,
  `tumblr_metrics_updated_on` datetime DEFAULT NULL,
  `twitter_shits` int(11) NOT NULL DEFAULT '0',
  `twitter_url` varchar(255) DEFAULT NULL,
  `twitter_metrics_updated_on` datetime DEFAULT NULL,
  `gotmesomebullshityall` int(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  UNIQUE KEY `slug_UNIQUE` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=104 DEFAULT CHARSET=utf8;


CREATE TABLE `history_of_things` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `collection` char(30) DEFAULT NULL,
  `thing_id` int(11) DEFAULT NULL,
  `value` varchar(45) DEFAULT NULL,
  `added` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1192 DEFAULT CHARSET=latin1;
